from __future__ import annotations

"""Colab-friendly training artifact generator.

The real GRPO/SFT model training is optional and GPU-dependent. This script is
kept dependency-light so every environment can still produce the judge-facing
artifacts: baseline scores, a stronger policy score, reward traces, and a demo
transcript. In Colab, run this before/after any Unsloth or TRL training cells so
there is always a reproducible reward-loop result to commit.
"""

import argparse
import json
import statistics
import sys
from pathlib import Path
from typing import Callable

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from gpu_budget_arena.baselines import (
    always_accept_policy,
    greedy_hoarder_policy,
    random_validish_policy,
    rule_based_expert_policy,
)
from gpu_budget_arena.env import GpuBudgetNegotiationEnv
from gpu_budget_arena.models import GpuNegotiationAction, GpuNegotiationObservation, ResetConfig

Policy = Callable[[GpuNegotiationObservation], GpuNegotiationAction]

TASK_TYPES = ["single_trade", "market_round", "coalition_market"]
BASELINE_POLICIES: dict[str, Policy] = {
    "random_validish": random_validish_policy,
    "greedy_hoarder": greedy_hoarder_policy,
    "always_accept": always_accept_policy,
}
COMPARISON_POLICIES: dict[str, Policy] = {
    **BASELINE_POLICIES,
    "rule_based_expert": rule_based_expert_policy,
}


def run_episode(task_type: str, seed: int, policy_name: str, policy: Policy) -> dict[str, object]:
    env = GpuBudgetNegotiationEnv()
    obs = env.reset(ResetConfig(task_type=task_type, seed=seed))
    rewards: list[float] = []
    invalid_actions = 0
    action_trace: list[dict[str, object]] = []

    while not obs.done:
        action = policy(obs)
        obs = env.step(action)
        rewards.append(obs.reward)
        if obs.last_action_result and not obs.last_action_result.ok:
            invalid_actions += 1
        action_trace.append(
            {
                "round_index": obs.round_index,
                "action": action.model_dump(mode="json", exclude_none=True),
                "reward": obs.reward,
                "result": obs.last_action_result.model_dump(mode="json") if obs.last_action_result else None,
            }
        )

    return {
        "task_type": task_type,
        "seed": seed,
        "policy": policy_name,
        "steps": len(rewards),
        "episode_reward": obs.cumulative_reward,
        "final_reward": obs.reward,
        "invalid_actions": invalid_actions,
        "reward_trace": rewards,
        "action_trace": action_trace,
    }


def summarize(records: list[dict[str, object]]) -> dict[str, object]:
    grouped: dict[str, dict[str, list[float]]] = {}
    invalids: dict[str, dict[str, int]] = {}
    for record in records:
        task_type = str(record["task_type"])
        policy = str(record["policy"])
        grouped.setdefault(task_type, {}).setdefault(policy, []).append(float(record["episode_reward"]))
        invalids.setdefault(task_type, {}).setdefault(policy, 0)
        invalids[task_type][policy] += int(record["invalid_actions"])

    summary: dict[str, object] = {}
    for task_type, policies in grouped.items():
        summary[task_type] = {
            policy: {
                "mean_reward": round(statistics.mean(scores), 4),
                "stdev_reward": round(statistics.pstdev(scores), 4),
                "episodes": len(scores),
                "invalid_actions": invalids[task_type][policy],
            }
            for policy, scores in sorted(policies.items())
        }
    return summary


def write_markdown_report(payload: dict[str, object], output: Path) -> None:
    lines = [
        "# Training Reward Report",
        "",
        "This report is generated by `training/train_grpo_stub.py`. The `rule_based_expert` row is a reproducible stand-in for the trained-policy slot when a GPU SFT/GRPO run is not available yet.",
        "",
        "| Task | Policy | Mean reward | Std dev | Episodes | Invalid actions |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    summary = payload["summary"]
    assert isinstance(summary, dict)
    for task_type, policy_rows in summary.items():
        assert isinstance(policy_rows, dict)
        for policy, stats in policy_rows.items():
            assert isinstance(stats, dict)
            lines.append(
                f"| `{task_type}` | `{policy}` | `{stats['mean_reward']}` | `{stats['stdev_reward']}` | `{stats['episodes']}` | `{stats['invalid_actions']}` |"
            )
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--seeds", type=int, default=10)
    parser.add_argument("--output", default="artifacts/training_eval.json")
    parser.add_argument("--report", default="artifacts/training_report.md")
    parser.add_argument(
        "--policy-set",
        choices=["comparison", "baselines"],
        default="comparison",
        help="Use 'comparison' for final artifacts; use 'baselines' for a faster smoke run.",
    )
    args = parser.parse_args()

    policies = COMPARISON_POLICIES if args.policy_set == "comparison" else BASELINE_POLICIES
    records = [
        run_episode(task_type, seed, policy_name, policy)
        for seed in range(args.seeds)
        for task_type in TASK_TYPES
        for policy_name, policy in policies.items()
    ]
    payload = {
        "description": "Reward-loop evaluation for Colab/GRPO handoff.",
        "seeds": args.seeds,
        "summary": summarize(records),
        "episodes": records,
    }

    output = Path(args.output)
    report = Path(args.report)
    output.parent.mkdir(parents=True, exist_ok=True)
    report.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    write_markdown_report(payload, report)
    print({"output": str(output), "report": str(report), "episodes": len(records)})
    print(json.dumps(payload["summary"], indent=2))


if __name__ == "__main__":
    main()
